package asia.sozo.sozobot.entity;

public enum UserState {
    START,
    LANG,
    MASTER_CLASS,
    MERCH,
    LOCATION,

    LOGIN_OR_REGISTER,
    LOGIN,
    REGISTER,
    LOGIN_ENTER_PASSWORD,
    REGISTER_ENTER_PASSWORD,
    REGISTER_ENTER_CONFIRM,
    REGISTER_ENTER_NAME,
    REGISTER_ENTER_SURNAME,
    LOGGED,
    REGISTERED,
    REGISTER_QUESTION,
    LOGIN_QUESTION,
    HOME,
    MENU,
    PROFILE,
    BASKET,
    ORDERS,
    PRODUCTS,
    CATALOG,
    CALCULATE_PREVIEW,
    DO_ORDER,
    CATEGORY,


}
